region              = "us-east-1"
profile             = "dev-profile"
foundation_model    = "anthropic.claude-v2"
lambda_arn          = "arn:aws:lambda:us-east-1:123456789012:function:minha-funcao"
schema_yaml_s3_uri  = "s3://meu-bucket/action-schema.yaml"